from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from io import BytesIO
from datetime import datetime

def generate_pdf_report(user_name, analysis_data):
    execution_start = datetime.now()
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    
    styles = getSampleStyleSheet()
    story = []

    # Title
    title_style = styles['Title']
    story.append(Paragraph("Financial Health Assessment Report", title_style))
    story.append(Spacer(1, 12))

    # Metadata
    normal_style = styles['Normal']
    story.append(Paragraph(f"<b>Generated for:</b> {user_name}", normal_style))
    story.append(Paragraph(f"<b>Date:</b> {execution_start.strftime('%Y-%m-%d %H:%M')}", normal_style))
    story.append(Spacer(1, 24))

    # Financial Summary
    story.append(Paragraph("Executive Summary", styles['Heading2']))
    story.append(Spacer(1, 12))

    summary = analysis_data.get("financial_summary", {})
    revenue = summary.get("revenue", {}).get("total", 0)
    expenses = summary.get("expenses", {}).get("total", 0)
    profit = summary.get("net_profit", 0)
    margin = (profit / revenue * 100) if revenue else 0
    health_score = summary.get("health_score", 0)
    risk_level = summary.get("risk_level", "Unknown")

    data = [
        ["Metric", "Value"],
        ["Total Revenue", f"${revenue:,.2f}"],
        ["Total Expenses", f"${expenses:,.2f}"],
        ["Net Profit", f"${profit:,.2f}"],
        ["Profit Margin", f"{margin:.1f}%"],
        ["Health Score", f"{health_score}/100"],
        ["Risk Assessment", risk_level]
    ]

    t = Table(data, colWidths=[200, 200])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (1, 0), colors.indigo),
        ('TEXTCOLOR', (0, 0), (1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
    ]))
    story.append(t)
    story.append(Spacer(1, 24))

    # Recommendations
    story.append(Paragraph("AI Recommendations", styles['Heading2']))
    story.append(Spacer(1, 12))
    
    recommendations = summary.get("recommendations", [])
    if not recommendations:
        story.append(Paragraph("No specific recommendations generated.", normal_style))
    else:
        for rec in recommendations:
            # Map keys to text if they are keys, or use text directly
            text = rec
            if rec == "REC_INCREASE_MARKETING": text = "Increase marketing spend by 10% to accelerate growth."
            if rec == "REC_RENEGOTIATE_CONTRACTS": text = "Renegotiate vendor contracts to reduce COGS."
            if rec == "REC_WORKING_CAPITAL": text = "Consider a short-term working capital loan for inventory expansion."
            
            bullet = Paragraph(f"• {text}", normal_style)
            story.append(bullet)
            story.append(Spacer(1, 6))

    # Footer or Disclaimer
    story.append(Spacer(1, 48))
    story.append(Paragraph("<i>Disclaimer: This report is generated by AI for informational purposes only. Consult a financial advisor for professional advice.</i>", styles['Italic']))

    doc.build(story)
    buffer.seek(0)
    return buffer
